// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";
// ...existing code...
// If DATABASE_URL isn't already in the process env, try to load a .env from the repo root
import fs from "fs";
import path from "path";
import dotenv from "dotenv";

const repoRootEnv = path.resolve(__dirname, "../../.env");
const localEnv = path.resolve(__dirname, ".env");

if (!process.env.DATABASE_URL) {
  if (fs.existsSync(repoRootEnv)) {
    dotenv.config({ path: repoRootEnv });
  } else if (fs.existsSync(localEnv)) {
    dotenv.config({ path: localEnv });
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
